### ISSUE TITLE
feat: 로더 및 스켈레톤 적용

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#10]
## Description
api 요청 후 응답을 기다리는 동안 사용자는 서비스가 동작하고 있는지 알지 못한다.
그렇기에 요청 후 응답을 기다리고 있다는, 즉 서비스가 동작하고 있다는 것을 알려줄 수 있도록 로딩 컴포넌트를 보여준다.

## Tasks

- [x] 홈의 agora list 로더 적용
- [x] 버튼 클릭 후 api 응답 대기 시 버튼에 로더 적용
- [x] 로더와 스켈레톤 적절히 사용

## References
- [카카오 스켈레톤 사용자 경험 개선](https://tech.kakaopay.com/post/skeleton-ui-idea/)
