### ISSUE TITLE
nextAuth로 사용자 세션 관리

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#104]
## Description
메모리로 관리하던 access token은 소셜 로그인 후 리다이렉트 되면서 메모리에서 사라지게 된다.
토큰을 가지고 있지 않으므로 api 요청할 때 refresh token으로 갱신시켜주면서 요청을 날리게 된다.
이 경우 불필요한 서버 요청이 추가되는 것이므로 nextAuth의 세션 관리를 사용하여 access token을 관리하는 것으로 변경하고자 한다.

## Tasks

- [x] 소셜 로그인 후 얻은 access token 메모리에서 auth.js에서 제공하는 세션관리로 변경
- [x] access token 만료시 refresh token으로 갱신 및 세션 update
- [x] refresh token 에러 혹은 만료시 로그아웃 진행 후 로그인 페이지로 이동

## References

- [auth.js 정리](https://www.heropy.dev/p/MI1Khc)
