### ISSUE TITLE
feat: 채팅방 소켓 연결

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#11]
## Description
실시간 채팅을 위한 소켓 연결 작업 수행

## Tasks

- [x] stomp 라이브러리 활용하여 connect
- [x] 메시지 보내기/받기
- [x] 전달받은 메타정보 갱신
