### ISSUE TITLE
feat: 채팅 api에 맞춰 데이터 수정

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#12]
## Description
초기에 작성된 api 명세서와 달라진 응답 데이터에 맞춰 수정

## Tasks

- [x] 채팅 응답 데이터에 맞춰 메시지 컴포넌트 수정
- [x] 메타 데이터 응답 데이터에 맞춰 컴포넌트 수정
- [x] 사용자 리스트 불러오기 응답 데이터 맞춰 수정
