### ISSUE TITLE
refactor: 아고라 입장하기 모달 코드 분리

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#14]
## Description
아고라 입장하기 모달 코드가 하나의 파일로 이루어져있다.
관련된 코드끼리 컴포넌트로 분리하고자 한다.

## Tasks

- [x] 닉네임 길이 제한 에러 메시지 컴포넌트 분리
- [x] 프로필 이미지 선택 컴포넌트 분리
- [x] 아고라 입장하기 버튼 컴포넌트 분리
