### ISSUE TITLE
feat: 아고라/채팅 에러처리

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#19]
## Description
채팅을 제외한 페이지에서 발생할 수 있는 에러 처리

## Tasks

- [x] 아고라 조회
- [x] 아고라 입장
- [x] 아고라 생성
- [x] 아고라 타이틀 조회
- [x] 아고라 Id 리스트 조회
- [x] 투표 결과 조회
- [x] 토론 시작하기
- [x] 토론 종료하기
- [x] 웹소켓
- [x] 채팅 리스트 조회

## References
-
