### ISSUE TITLE
fix: api 요청 에러 발생시 무한 재시도 에러

### ISSUE THREAD

**Issue by ldh-dodo** [Attica-org/athens-client#23]
## Description
fetchWrapper 파일에서 API 요청 에러가 발생했을 때, API 요청이 무한 시도 되는 에러가 발생함.

## Tasks

- [x] 무한 재시도 수정
- [x] 재시도 횟수 초과시 에러 응답 메시지 작성
- [x] custom error 추가
- [x] Get요청 lib 파일에 재시도 에러에 대한 핸들링
