### ISSUE TITLE
feat: 아고라 강제종료 api 연동

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#26]
## Description
토론 타임아웃시 서버와의 동기화가 안되어 있어, 토론이 종료되었는지 알지 못하는 문제가 있다.
타임아웃 이벤트 발생시, 클라이언트에서 아고라 종료 api를 호출하여 서버에게 상태 변경을 요청한다.

## Tasks

- [x] 아고라 강제종료 api 연동
- [x] 아고라 강제종료 api 에러캐치
- [x] 채팅 추가된 에러 코드 처리
