### ISSUE TITLE
refactor: 종료된 아고라 소켓 미연결 실시간 정보 숨김

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#35]
## Description
종료된 아고라의 경우 소켓 연결이 필요하지 않다.
또한, 메시지를 전송하지 않기 때문에, 알림 메시지를 출력할 필요가 없다.

## Tasks

- [x] 종료된 아고라 소켓 미연결
- [x] 종료된 아고라 알림 메시지 미출력
- [x] 데스크탑 모드 공유 모달 로고 이름 가려짐
