### ISSUE TITLE
feat: mock api 서비스 제작하여 기능 연결

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#5]
## Description
백엔드로부터 api를 받기 전까지 mock api를 사용하여 기능을 연결한다.
소켓을 제외한 일반 http api에 대해 적용한다.

## Tasks

- [x] 홈 mock api 적용
- [x] 모달 mock api 적용
- [x] 채팅 소켓을 제외한 일반 http api 적용
- [x] 아고라 생성 mock api 적용
