### ISSUE TITLE
QA1 채팅방 오류 수정

### ISSUE THREAD

**Issue by ldh-dodo** [Attica-org/athens-client#53]
## Description
채팅방에서 발생한 여러 오류들을 수정한다.
## Tasks

- [x] 종료 투표 후 한번 더 누르면 reissue요청이 계속 가는 문제 수정
- [x] service worker 탭 여러개 켜놨을 때 vote 무작위로 가는문제 수정
- [x] service worker 투표 종료 타이머 동기화
- [x] 채팅방 toast 알림 텍스트 작게 수정
- [x] 카카오 공유하기 title undefined 수정
