### ISSUE TITLE
추가 요구사항

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#54]
## Description
- 종료된 아고라 리스트는 참여중인 사용자가 0명이기 때문에(찬/반), 참여 인원이 아닌 투표 결과를 출력하고자 한다.

- 또한, 디바이스에서 제공하는 공유 기능을 사용할 수 있을 땐 해당 기능을 사용하는 것으로 적용했지만, 
그렇게 되면 사용자마다 볼 수 있는 공유 화면이 달라지게 된다.
특히, 데스크탑 모드일 땐 기본적으로 제공되는 공유 기능이 많지 않기에 모바일과 다르게 보일 확률이 크다.
그렇기에 일관성있게 직접 만든 공유 모달을 띄우는 것으로 변경한다.

## Tasks

- [x] 종료된 아고라는 리스트에 투표 결과 출력
- [x] `아고라가 존재하지 않는다` 텍스트 가운데로 출력
- [x] 디바이스에서 제공하는 공유 기능이 아닌 공유 모달 페이지 뜨도록 변경

## References

-
