### ISSUE TITLE
QA1 추가 문제점 수정

### ISSUE THREAD

**Issue by ldh-dodo** [Attica-org/athens-client#62]
## Tasks

- [x] 토큰 재발급시 토큰 미저장 문제
- [x] 토론 종료시 유저 목록 초기화
- [x] 종료된 아고라 키워드 검색 후 입장시 모달 거치지 않도록 수정
- [x] service worker 미작동 문제
