### ISSUE TITLE
v1 리팩토링

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#66]
## Description
홈화면, 채팅화면에서의 성능에 문제가 될 수 있는 부분을 찾아 리팩토링한다.

- 채팅방은 아고라 리스트와 다르게 데이터가 빠른 속도가 쌓이게 된다.
이는 DOM에도 똑같이 적용되며, DOM에 쌓인 데이터가 많을 수록 성능 저하가 발생하게 된다.
이를 해결하기 위해 채팅방의 채팅 리스트에 virtual scroll를 적용하도록 한다.

## Tasks

- [x] 채팅방 사용자 리스트 모달이 열려있을 때만 meta 데이터 refetch 되도록 변경
- [x] 홈 화면 카테고리 및 키워드 검색 시 항상 전체 페이지 리렌더링 문제 수정
- [x] 채팅 화면 virtual scroll 적용
- [x] 홈 화면 virtual scroll 적용
- [x] 함수 이름 수정
- [x] 응집도 / 결합도 고려
- [x] custom hook
- [x] 타입 추출 및 관리

## References

-
