### ISSUE TITLE
인기 아고라/이미지 업로드/투표 종료 그래프 서버 데이터 연동

### ISSUE THREAD

**Issue by H-sooyeon** [Attica-org/athens-client#82]
## Description
제작해놓은 UI에 배포된 서버의 데이터를 연동하여 일관된 데이터를 볼 수 있도록 한다.
아고라 이미지를 수정할 수 있도록 한다.

## Tasks

- [x] 인기 아고라 서버 연동
- [x] 이미지 업로드 서버 연동
- [x] 아고라 이미지 수정
- [x] 투표 종료 그래프 서버 연동

## References

- []()
