### ISSUE TITLE
유저 설정 페이지 구현

### ISSUE THREAD

**Issue by ldh-dodo** [Attica-org/athens-client#94]
## Description
유저 프로필 확인 및 로그아웃, 탈퇴를 위한 유저 설정 페이지 구현

## Tasks

- [x]  UI 제작
- [x] 유저 정보 보여주기 기능 구현
- [x] 로그아웃 기능 구현
- [x] 탈퇴하기 기능 구현

## References

- []()
