### ISSUE TITLE
v2 기능구현

### ISSUE THREAD

**Issue by ldh-dodo** [Attica-org/athens-client#95]
## Description
v2에 추가된 기능들을 구현
## Tasks

- [x] 비속어 필터 기능 구현
- [x] 아고라 입장 / 퇴장 알림 기능 구현
- [x] 채팅 나가기 기능 구현
- [x] 채팅 반응하기 기능 구현
- [x] 아고라 강퇴 투표 기능 구현

## References

- [sample](https://www.google.com/)
